AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Multi-Armed Bandit Pricing Engine

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    MemorySize: 512
    Environment:
      Variables:
        DYNAMO_TABLE_ARMS: "PricingArms"
        DYNAMO_TABLE_LOG:  "ImpressionsLog"

Resources:
  # 1) Define an explicit API Gateway (Serverless::Api) with CORS
  PricingEngineApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"

  # 2) SelectPriceFunction, using the explicit API above
  SelectPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: select_price.app
      Role: arn:aws:iam::861985335071:role/LambdaPricingBanditRole
      Events:
        GetPriceAPI:
          Type: Api
          Properties:
            RestApiId: !Ref PricingEngineApi
            Path: /getPrice
            Method: get

  # 3) ReportOutcomeFunction, using the same explicit API
  ReportOutcomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: report_outcome.app
      Role: arn:aws:iam::861985335071:role/LambdaPricingBanditRole
      Events:
        ReportOutcomeAPI:
          Type: Api
          Properties:
            RestApiId: !Ref PricingEngineApi
            Path: /reportOutcome
            Method: post

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${PricingEngineApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
